#=====================================================
# linear source
#=====================================================

/gate/source/addSource linear gps

/gate/source/linear/gps/type Point 
/gate/source/linear/gps/pos/centre 0 0 0 cm

/gate/source/linear/setActivity 0 Bq
/gate/source/linear/setType backtoback
/gate/source/linear/gps/particle gamma
/gate/source/linear/gps/ene/mono 511. keV
/gate/source/linear/gps/angtype iso

/gate/source/list
