# G A M M A   P H O T O N S

/gate/digitizer/Singles/insert                        adder
/gate/digitizer/Singles/insert                        readout
/gate/digitizer/Singles/readout/setDepth              1

/gate/digitizer/name                                  Singles_S1 
/gate/digitizer/insert                                singleChain
/gate/digitizer/Singles_S1/setInputName               Singles

/gate/digitizer/Singles/insert                        blurring
/gate/digitizer/Singles/blurring/setResolution        0.26
/gate/digitizer/Singles/blurring/setEnergyOfReference 511. keV

/gate/digitizer/Singles/insert                        thresholder
/gate/digitizer/Singles/thresholder/setThreshold      350. keV
/gate/digitizer/Singles/insert                        upholder
/gate/digitizer/Singles/upholder/setUphold            650. keV

# O P T I C A L   P H O T O N S

/gate/digitizer/Singles_S1/insert                     opticaladder
/gate/digitizer/Singles_S1/insert                     readout
/gate/digitizer/Singles_S1/readout/setDepth           1
