#=====================================================
# VISUALISATION
#=====================================================

#/vis/disable
/vis/enable
/control/execute ../../Visualisation.mac

#=====================================================
# MATERIALS
#=====================================================

/gate/geometry/setMaterialDatabase ../../materials/GateMaterials.db

#=====================================================
# GEOMETRY
#=====================================================

# 4 mm
/control/execute ../../geometries/D85/Geometry_D85_1lay_L020_4mm.mac
#/control/execute ../../geometries/D85/Geometry_D85_1lay_L050_4mm.mac
#/control/execute ../../geometries/D85/Geometry_D85_1lay_L100_4mm.mac

# 7 mm
#/control/execute ../../geometries/D85/Geometry_D85_1lay_L020_7mm.mac
#/control/execute ../../geometries/D85/Geometry_D85_1lay_L050_7mm.mac
#/control/execute ../../geometries/D85/Geometry_D85_1lay_L100_7mm.mac

#=====================================================
# PHYSICS
#=====================================================

/control/execute ../../physics/PhysicsEMLivermorePolar.mac

#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize

#=====================================================
#  P A R T I C L E   S O U R C E
#=====================================================

/control/execute sources/PMB_Spatial_Resolution/Source_Sphere_Gamma_01_00_00.mac
#/control/execute sources/PMB_Spatial_Resolution/Source_Sphere_Gamma_10_00_00.mac
#/control/execute sources/PMB_Spatial_Resolution/Source_Sphere_Gamma_20_00_00.mac

# L020 (source position at 7.5 cm from the centre of the scanner along the z axis)
#/control/execute sources/PMB_Spatial_Resolution/Source_Sphere_Gamma_L020_01_00_07.mac
#/control/execute sources/PMB_Spatial_Resolution/Source_Sphere_Gamma_L020_10_00_07.mac
#/control/execute sources/PMB_Spatial_Resolution/Source_Sphere_Gamma_L020_20_00_07.mac

# L050 (source position at 18.75 cm from the centre of the scanner along the z axis)
#/control/execute sources/PMB_Spatial_Resolution/Source_Sphere_Gamma_L020_01_00_19.mac
#/control/execute sources/PMB_Spatial_Resolution/Source_Sphere_Gamma_L020_10_00_19.mac
#/control/execute sources/PMB_Spatial_Resolution/Source_Sphere_Gamma_L020_20_00_19.mac

# L050 (source position at 37.5 cm from the centre of the scanner along the z axis)
#/control/execute sources/PMB_Spatial_Resolution/Source_Sphere_Gamma_L020_01_00_37.mac
#/control/execute sources/PMB_Spatial_Resolution/Source_Sphere_Gamma_L020_10_00_37.mac
#/control/execute sources/PMB_Spatial_Resolution/Source_Sphere_Gamma_L020_20_00_37.mac

#=====================================================
#  D A T A   O U T P U T   
#=====================================================

/control/execute Output.mac

#=====================================================
#   R A N D O M
#=====================================================

/gate/random/setEngineName MersenneTwister
#/gate/random/setEngineSeed 123456789
/gate/random/setEngineSeed auto
#/gate/random/verbose 1

#=====================================================
#   M E A S U R E M E N T   S E T T I N G S   
#=====================================================

/gate/application/setTimeSlice   1 s
/gate/application/setTimeStart   0 s
/gate/application/setTimeStop    100 s
/gate/application/startDAQ
