#=====================================================
# point source
#=====================================================

/gate/source/addSource point gps

/gate/source/point/gps/type Point
/gate/source/point/gps/pos/centre 0 0 0 cm

/gate/source/point/setActivity 0 Bq
/gate/source/point/setType backtoback
/gate/source/point/gps/particle gamma
/gate/source/point/gps/ene/mono 511. keV
/gate/source/point/gps/angtype iso

/gate/source/list
