name: build-test

on: [push, pull_request]

jobs:

  build-test:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Install dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y git libboost-all-dev libtbb-dev cmake

    - name: download  ROOT (for ubuntu-20.04)
      run: |
        wget https://root.cern/download/root_v6.24.00.Linux-ubuntu20-x86_64-gcc9.3.tar.gz
        mkdir -p cern-root
        tar xzf root_v6.24.00.Linux-ubuntu20-x86_64-gcc9.3.tar.gz -C cern-root
        source cern-root/root/bin/thisroot.sh

    - name: Build goja
      run: |
        source cern-root/root/bin/thisroot.sh
        cd goja
        mkdir build
        cd build
        cmake ..
        make $(nproc)
